### ISSUE TITLE
docker don't start

### ISSUE THREAD

**Issue by StephanKrauss** [kb05/template-docker-apache-php-xdebug#1]
Hello,

i have tested your script.
I get a error message.

Here is my docker-compose:
```
version: "3"
services:
  phpserver:
    image: php7.4_xdebug:latest
    restart: "no"
    build:
        context: ./images/php
        dockerfile: Dockerfile
        args:
          - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ../project:/var/www/html
      - ./volumenes/apache/sites-enabled:/etc/apache2/sites-enabled
    ports:
      - ${HTTP_SERVER_PORT}:80
```

and here my .env file:
```
#Services ports

# The apache port
HTTP_SERVER_PORT=80

# The PHP version
PHP_VERSION=7.4
```

When i start 'docker-compose up -d' the script build the image.
I get the message: 'Starting docker_phpserver_1 ... done'

But the docker container is not starting. When i look in the logs i see the info:
'Error response from daemon: configured logging driver does not support reading'

I work under windows 10 with docker desktop.

Can you help ?

Your sincerly

Stephan
